[build-system]
requires = ["flit_core >=3.11,<4"]
build-backend = "flit_core.buildapi"

[project]
name = "ChlCONNECT"
authors = [{name = "ManhTRAN", email = "manh.tran-duy@univ-littoral.fr"}]
readme = "README.md"
license = "MIT"
license-files = ["LICENSE"]
dynamic = ["version", "description"]
